// Code generated by "stringer -type=UnicodeCategory"; DO NOT EDIT.

package main

import "strconv"

const _UnicodeCategory_name = "controldigitgraphicletterlowermarknumberprintpunctspacesymboltitleupperinvalid"

var _UnicodeCategory_index = [...]uint8{0, 7, 12, 19, 25, 30, 34, 40, 45, 50, 55, 61, 66, 71, 78}

func (i UnicodeCategory) String() string {
	if i < 0 || i >= UnicodeCategory(len(_UnicodeCategory_index)-1) {
		return "UnicodeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnicodeCategory_name[_UnicodeCategory_index[i]:_UnicodeCategory_index[i+1]]
}
